### PR TITLE
Fixed Swift 4.0.3 warnings

### PR DESCRIPTION
**Pull request by valeriomazzeo**

### CODE REVIEW

**Review by vzsg — CHANGES_REQUESTED** [review]
Please make sure that the change doesn't break on Swift 3. You can copy the workaround from [here](https://github.com/vapor/node/pull/98/files).

**Comment by valeriomazzeo** [comment]
done 👍

**Comment by Joannis** [comment]
This is not compiling on the CI

**Comment by valeriomazzeo** [comment]
@Joannis my bad sorry, last commit should fix it.

**Comment by vzsg** [comment]
I fixed CircleCI on master and updated this branch.
As the test shows, the last fix didn't work out.

**Review by vzsg — APPROVED** [review]

**Comment by vzsg** [comment]
Nice, thank you for the perseverance!

**Pull request merged**
