### PR TITLE
Update to MongoKitten 3 and support latest fluent count() feature

### PR DESCRIPTION
**Pull request by fedefrappi**
I built this on top of @Joannis #26  by updating to the official mongokitten 3 release and fixing some other issues (e.g. missing bson to bool conversion).
I also added support for the count() feature recently added to fluent. 
Finally the underlying mongokitten driver is now public so that users are able to use it directly for implementing features currently not available on fluent (e.g. geoqueries and indexes).

### CODE REVIEW

**Comment by Joannis** [comment]
I didn't read the code, but I completely agree with the changes you've noted down in the commits and the accessibility of the underlying driver.

**Comment by tanner0101** [comment]
@fedefrappi this looks great.

@Joannis is MongoKitten 3 officially released?

**Comment by Joannis** [comment]
@tannernelson it sure is!

**Comment by Joannis** [comment]
I'd prefer the next tag (if it's a major one) to also cover ObjectId properly. Currently people that make references between databases have the problem that `ObjectId` is converted to a `Node.string` but the reverse isn't possible. I'm thinking the ExtendedJSON approach might be fit for this task.

**Comment by tanner0101** [comment]
Has this been tested on macOS and Linux? Unfortunately this repo doesn't have travis setup yet.. I'd definitely like to verify everything checks out before we tag it.

**Comment by fedefrappi** [comment]
The compiler started segfaulting with one of the latest releases but it is fixed now.
All tests pass on macOS (some are new with this pull requests).
Do you have a quick way for running the tests on Linux as well?

**Comment by Joannis** [comment]
@fedefrappi we had a bug in MongoKitten recently causing the compiler not to be able type check an initializer without crashing. That's solved now.

**Comment by fedefrappi** [comment]
@Joannis thanks! I just tried updating all packages and all tests are still passing fine :)

**Comment by tanner0101** [comment]
@fedefrappi I invited you to the Fluent team. Once accepted, could you move this PR on a branch in this repo?

This will help me test so we can get this merged. Thank you. :)

**Comment by fedefrappi** [comment]
@tannernelson sure but I don't think I received the invitation? Thanks!

**Comment by vzsg** [comment]
I had that too, be sure to check https://github.com/vapor, the invitation should pop up in the header section.

**Comment by fedefrappi** [comment]
@vzsg thanks that worked! I'll move the pull request to another branch soon :)

**Comment by fedefrappi** [comment]
@tannernelson new branch created and base branch changed, will you take it from here?

**Pull request merged**
